# This file goes to: .github/workflows/metrics.yml in your TheSeydiCharyyev/TheSeydiCharyyev repo

name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  # ==============================================
  # HEADER - Main profile overview
  # ==============================================
  header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-header.svg
          user: TheSeydiCharyyev
          template: classic
          base: header, activity, community, repositories
          base_indepth: yes
          config_timezone: Asia/Ashgabat
          config_display: large
          config_padding: 0, 8 + 11%

  # ==============================================
  # ISOMETRIC CALENDAR - 3D commit visualization
  # ==============================================
  isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-isocalendar.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  # ==============================================
  # ACHIEVEMENTS - GitHub achievements
  # ==============================================
  achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-achievements.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

  # ==============================================
  # LANGUAGES - Detailed language breakdown
  # ==============================================
  languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-languages.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_indepth: yes

  # ==============================================
  # HABITS - Coding habits and patterns
  # ==============================================
  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-habits.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes

  # ==============================================
  # ACTIVITY - Recent activity
  # ==============================================
  activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-activity.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes

  # ==============================================
  # NOTABLE - Notable contributions
  # ==============================================
  notable:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-notable.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit

  # ==============================================
  # LINES OF CODE - Code statistics
  # ==============================================
  lines:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-lines.svg
          user: TheSeydiCharyyev
          template: classic
          base: repositories
          config_timezone: Asia/Ashgabat
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

  # ==============================================
  # STARGAZERS - Stars evolution chart
  # ==============================================
  stargazers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-stargazers.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic

  # ==============================================
  # PEOPLE - Followers and following
  # ==============================================
  people:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-people.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

  # ==============================================
  # REPOSITORIES - Pinned repos
  # ==============================================
  repositories:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-repositories.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_repositories: yes
          plugin_repositories_featured: TheSeydiCharyyev/portfolio, TheSeydiCharyyev/flutter-outpatient-hospital-app, TheSeydiCharyyev/TurkmenPhrasebook

  # ==============================================
  # FOLLOW-UP - Issues and PRs
  # ==============================================
  followup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-followup.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

  # ==============================================
  # REACTIONS - Comment reactions
  # ==============================================
  reactions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-reactions.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100

  # ==============================================
  # CODE SNIPPET - Random code
  # ==============================================
  code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-code.svg
          user: TheSeydiCharyyev
          template: classic
          base: ""
          config_timezone: Asia/Ashgabat
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public

  # ==============================================
  # FULL PROFILE - Everything combined (alternative)
  # ==============================================
  full:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-full.svg
          user: TheSeydiCharyyev
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Ashgabat
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_stars: yes
          plugin_stars_limit: 4
